wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 256
d_model:
  value: 64
log_learning_rate:
  value: -2.4796744178204326
n_heads:
  value: 2
n_layers:
  value: 4
optimizer:
  value: AdamW
