wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 32
log_learning_rate:
  value: -2.5271289625184536
n_heads:
  value: 2
n_layers:
  value: 1
optimizer:
  value: AdamW
