wandb_version: 1

log_learning_rate:
  desc: null
  value: -7.600902459542082
batch_size:
  desc: null
  value: 256
n_layers:
  desc: null
  value: 2
d_model:
  desc: null
  value: 32
n_heads:
  desc: null
  value: 2
act:
  desc: null
  value: selu
optimizer:
  desc: null
  value: AdamW
architecture:
  desc: null
  value: Transformer
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690558241.980021
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.3
      5: 0.15.5
      8:
      - 1
      - 5
