wandb_version: 1

act:
  desc: null
  value: selu
architecture:
  desc: null
  value: Transformer
batch_size:
  desc: null
  value: 512
d_model:
  desc: null
  value: 128
log_learning_rate:
  desc: null
  value: -1.492506680463288
n_heads:
  desc: null
  value: 8
n_layers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: AdamW
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690540713.749246
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.3
      5: 0.15.5
      8:
      - 5
