wandb_version: 1

batch_size:
  desc: null
  value: 1024
context_len:
  desc: null
  value: 3
embed_dim:
  desc: null
  value: 32
hidden_dim:
  desc: null
  value: 100
log_learning_rate:
  desc: null
  value: -3.9936944244920527
optimizer:
  desc: null
  value: AdamW
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689319574.225726
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.3
      5: 0.15.5
      8:
      - 5
