wandb_version: 1

act:
  desc: null
  value: gelu
architecture:
  desc: null
  value: Transformer
batch_size:
  desc: null
  value: 256
d_model:
  desc: null
  value: 64
log_learning_rate:
  desc: null
  value: -2.4796744178204326
n_heads:
  desc: null
  value: 2
n_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: AdamW
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690539243.328933
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.15.5
      8:
      - 5
