wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 32
log_learning_rate:
  value: -2.6799626874909723
n_heads:
  value: 1
n_layers:
  value: 2
optimizer:
  value: AdamW
