wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 32
log_learning_rate:
  value: -1.1209454500778286
n_heads:
  value: 4
n_layers:
  value: 2
optimizer:
  value: AdamW
