wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 128
log_learning_rate:
  value: -1.3162213756586203
n_heads:
  value: 8
n_layers:
  value: 4
optimizer:
  value: AdamW
