wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 256
d_model:
  value: 128
log_learning_rate:
  value: -3.319891789402007
n_heads:
  value: 4
n_layers:
  value: 1
optimizer:
  value: AdamW
