wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 256
d_model:
  value: 32
log_learning_rate:
  value: -3.636116566626544
n_heads:
  value: 1
n_layers:
  value: 2
optimizer:
  value: AdamW
