wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 256
d_model:
  value: 64
log_learning_rate:
  value: -2.675987323931064
n_heads:
  value: 2
n_layers:
  value: 2
optimizer:
  value: AdamW
