wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 64
log_learning_rate:
  value: -3.398347053090956
n_heads:
  value: 8
n_layers:
  value: 1
optimizer:
  value: AdamW
