wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 32
log_learning_rate:
  value: -3.7934481132250055
n_heads:
  value: 8
n_layers:
  value: 1
optimizer:
  value: AdamW
