wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 256
d_model:
  value: 64
log_learning_rate:
  value: -3.061082528577814
n_heads:
  value: 8
n_layers:
  value: 4
optimizer:
  value: AdamW
