wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 256
d_model:
  value: 64
log_learning_rate:
  value: -3.8007001212339167
n_heads:
  value: 4
n_layers:
  value: 4
optimizer:
  value: AdamW
