wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 128
log_learning_rate:
  value: -2.644197922752874
n_heads:
  value: 2
n_layers:
  value: 4
optimizer:
  value: AdamW
