wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 32
log_learning_rate:
  value: -1.743682004708163
n_heads:
  value: 4
n_layers:
  value: 2
optimizer:
  value: AdamW
