wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 128
log_learning_rate:
  value: -1.492506680463288
n_heads:
  value: 8
n_layers:
  value: 1
optimizer:
  value: AdamW
