wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 64
log_learning_rate:
  value: -2.8456316088327207
n_heads:
  value: 8
n_layers:
  value: 1
optimizer:
  value: AdamW
