wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 64
log_learning_rate:
  value: -1.3527801564983246
n_heads:
  value: 8
n_layers:
  value: 2
optimizer:
  value: AdamW
