wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 32
log_learning_rate:
  value: -3.204690656859623
n_heads:
  value: 8
n_layers:
  value: 4
optimizer:
  value: AdamW
