wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 128
log_learning_rate:
  value: -2.228681405316377
n_heads:
  value: 4
n_layers:
  value: 2
optimizer:
  value: AdamW
