wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 512
d_model:
  value: 64
log_learning_rate:
  value: -2.326002234054797
n_heads:
  value: 1
n_layers:
  value: 4
optimizer:
  value: AdamW
