wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 64
log_learning_rate:
  value: -2.1847041501553512
n_heads:
  value: 4
n_layers:
  value: 1
optimizer:
  value: AdamW
