wandb_version: 1

act:
  value: selu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 128
log_learning_rate:
  value: -1.0803884845430185
n_heads:
  value: 2
n_layers:
  value: 4
optimizer:
  value: AdamW
