wandb_version: 1

act:
  value: gelu
architecture:
  value: Transformer
batch_size:
  value: 1024
d_model:
  value: 128
log_learning_rate:
  value: -2.851841503164807
n_heads:
  value: 2
n_layers:
  value: 1
optimizer:
  value: AdamW
